FROM influxdb:latest

# Copy initialization script and initial data into the container
COPY init_influxdb.sh /docker-entrypoint-initdb.d/init_influxdb.sh
COPY initial_data.csv /docker-entrypoint-initdb.d/initial_data.csv

# Make the initialization script executable
RUN chmod +x /docker-entrypoint-initdb.d/init_influxdb.sh
