FROM python:3.9

WORKDIR /app

COPY ./requirements.txt /requirements.txt

# Install dependencies
RUN pip install --no-cache-dir --upgrade -r /requirements.txt

COPY ./app /app/

# Generate gRPC code
RUN python -m grpc_tools.protoc -I=. --python_out=. --grpc_python_out=. src/server/proto/metric_service.proto
