FROM python:3.9

WORKDIR /app

COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY ./app /app/

RUN python -m grpc_tools.protoc -I=. --python_out=. --grpc_python_out=. server/proto/metric_service.proto

# CMD [ "python", "main.py" ]