version: '3.7'

services:
  fastapi:
    build: ./fastapi
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    env_file:
      - ./fastapi/.env
    depends_on:
      - grpc_server
    command: ["python", "manage.py", "runserver", "${FASTAPI_PORT}"]

  grpc_server:
    build: ./grpc_server
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    env_file:
      - ./grpc_server/.env
    depends_on:
      - influxdb
    command: ["python", "manage.py", "runserver", "${GRPC_PORT}"]
  
  influxdb:
    build: ./influxDB
    ports:
      - "${INFLUXDB_PORT}:${INFLUXDB_PORT}"
    env_file:
      - ./influxdb/.env
    # environment:
    #   - DOCKER_INFLUXDB_INIT_MODE=setup
    #   - DOCKER_INFLUXDB_INIT_USERNAME=myuser
    #   - DOCKER_INFLUXDB_INIT_PASSWORD=mypassword
    #   - DOCKER_INFLUXDB_INIT_ORG=spectral
    #   - DOCKER_INFLUXDB_INIT_BUCKET=spectral
    #   - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken