version: '3.7'

services:
  fastapi:
    build: ./fastapi
    ports:
      - 8000:8000
    depends_on:
      - grpc_server
    command: ["python", "manage.py", "runserver", "8000"]

  grpc_server:
    build: ./grpc_server
    ports:
      - 50051:50051
    depends_on:
      - influxdb
    command: ["python", "manage.py", "runserver"]
  
  influxdb:
    build: ./influxDB
    ports:
      - '8086:8086'
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=myuser
      - DOCKER_INFLUXDB_INIT_PASSWORD=mypassword
      - DOCKER_INFLUXDB_INIT_ORG=spectral
      - DOCKER_INFLUXDB_INIT_BUCKET=spectral
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken